### ISSUE TITLE
Add new pages and add text to existing pages, from updated spreadsheet

### ISSUE THREAD

**Issue by cwulfman** [TrustTheVote-Project/MarkIt-External-Website-Example#1]
Anne revised the website spreadsheet and added in red what is missing: there are 3 missing pages to create and there are 3 pages already created and no text on them. https://docs.google.com/spreadsheets/d/1tsCK2B0dCiM_cVDu_YDWx3SxwCXWEodMQYkSTKAwXq8/edit#gid=0

**Comment by trustthevote** [comment]
Cliff, I see that but is it now complete for you to fill in the 3 pages with missing text, and also to add the 3 new pages with the proper text? Please see also the comment to you I embedded in the sheet
